packages:
- .
resolver: lts-13.01

#resolver: lts-7.19
#compiler: ghcjs-0.2.1.9007019_ghc-8.0.1
#compiler-check: match-exact

#setup-info:
  #ghcjs:
    #source:
      #ghcjs-0.2.1.9007019_ghc-8.0.1:
           #url: http://ghcjs.tolysz.org/ghc-8.0-2017-02-05-lts-7.19-9007019.tar.gz
           #sha1: d2cfc25f9cda32a25a87d9af68891b2186ee52f9

extra-deps:
#- ../graph
- git: https://github.com/tosku/graph
  commit: 827fc93a4d432bd827ac6969087d6d7e61eda93a
- git: https://github.com/tosku/tesths
  commit: 0fb1ba49641e87b843556cd1441240ef602fcf2b
- git: https://github.com/tosku/prng
  commit: 3f93c3a3afc032212e101197c8f8b7d00c5772f3 
- Unique-0.4.7.2
- natural-numbers-0.1.2.0
- either-unwrap-1.1
allow-newer: true
